### ISSUE TITLE
After server starts, first new activity submit redirect doesn't work

### ISSUE THREAD

**Issue by loopified** [lambdaisland/activities#3]
Steps to reproduce:
Start the server, login, fill a new activity form and submit.

What I expect:
New activity page will show.

What happens:
NullPointerException error.

Refreshing the error page returns the proper activity page. After that, creating new activities work as intended.

**Comment by plexus** [comment]
We'll look at this together. Next time you file a bug like this though make sure to include a stack trace.

**Comment by loopified** [comment]
Stacktrace:

```
java.lang.NullPointerException
	at java.base/java.lang.Class.isAssignableFrom(Native Method)
	at java_time.graph$assignable_type_QMARK_.invokeStatic(graph.clj:61)
	at java_time.graph$assignable_type_QMARK_.invoke(graph.clj:60)
	at java_time.graph$fn__23332.invokeStatic(graph.clj:71)
	at java_time.graph$fn__23332.invoke(graph.clj:66)
	at java_time.potemkin.util$fast_memoize$fn__23244.invoke(util.clj:50)
	at java_time.graph$has_source_type_QMARK_$contains_src_types_QMARK___23570$fn__23571.invoke(graph.clj:279)
	at clojure.core$some.invokeStatic(core.clj:2701)
	at clojure.core$some.invoke(core.clj:2692)
	at java_time.graph$has_source_type_QMARK_$contains_src_types_QMARK___23570.invoke(graph.clj:279)
	at java_time.graph$has_source_type_QMARK_.invokeStatic(graph.clj:281)
	at java_time.graph$has_source_type_QMARK_.invoke(graph.clj:277)
	at java_time.graph$fn__23597.invokeStatic(graph.clj:301)
	at java_time.graph$fn__23597.invoke(graph.clj:300)
	at java_time.potemkin.util$fast_memoize$fn__23244.invoke(util.clj:52)
	at java_time.graph$conversion_fn.invokeStatic(graph.clj:316)
	at java_time.graph$conversion_fn.invoke(graph.clj:312)
	at java_time.local$local_date_time.invokeStatic(local.clj:52)
	at java_time.local$local_date_time.invoke(local.clj:52)
	at activities.views$activity_page.invokeStatic(views.clj:161)
	at activities.views$activity_page.invoke(views.clj:154)
	at activities.handlers$get_activity.invokeStatic(handlers.clj:66)
	at activities.handlers$get_activity.invoke(handlers.clj:65)
	at clojure.lang.Var.invoke(Var.java:384)
	at reitit.ring$ring_handler$fn__28275.invoke(ring.cljc:292)
	at activities.system$fn__35002$fn__35003.invoke(system.clj:88)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at user$wrap_capture_request_response$fn__169.invoke(user.clj:55)
	at activities.system$wrap_inject_crux$fn__35008.invoke(system.clj:92)
	at buddy.auth.middleware$wrap_authentication$fn__32200.invoke(middleware.clj:60)
	at ring.middleware.flash$wrap_flash$fn__28349.invoke(flash.clj:39)
	at ring.middleware.session$wrap_session$fn__29560.invoke(session.clj:108)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__29606.invoke(keyword_params.clj:53)
	at ring.middleware.nested_params$wrap_nested_params$fn__29664.invoke(nested_params.clj:89)
	at ring.middleware.multipart_params$wrap_multipart_params$fn__29962.invoke(multipart_params.clj:173)
	at ring.middleware.params$wrap_params$fn__29986.invoke(params.clj:67)
	at ring.middleware.cookies$wrap_cookies$fn__29439.invoke(cookies.clj:175)
	at ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__30157.invoke(absolute_redirects.clj:47)
	at ring.middleware.resource$wrap_resource_prefer_resources$fn__30022.invoke(resource.clj:25)
	at ring.middleware.content_type$wrap_content_type$fn__30105.invoke(content_type.clj:34)
	at ring.middleware.default_charset$wrap_default_charset$fn__30129.invoke(default_charset.clj:31)
	at ring.middleware.not_modified$wrap_not_modified$fn__30086.invoke(not_modified.clj:61)
	at ring.middleware.x_headers$wrap_x_header$fn__28312.invoke(x_headers.clj:22)
	at ring.middleware.x_headers$wrap_x_header$fn__28312.invoke(x_headers.clj:22)
	at ring.middleware.x_headers$wrap_x_header$fn__28312.invoke(x_headers.clj:22)
	at prone.middleware$wrap_exceptions$fn__30465.invoke(middleware.clj:159)
	at org.httpkit.server.HttpHandler.run(RingHandler.java:115)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
